# deploy.yml

name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/shop
            git fetch origin
            git reset --hard origin/main
            
            # Docker 빌드 전에, GitHub Secret 값을 사용해서 EC2 서버에 .env.production 파일을 생성합니다.
            echo "REACT_APP_WEBSOCKET_URL=${{ secrets.REACT_APP_WEBSOCKET_URL }}" > ./frontend/.env.production

            docker compose down
            docker compose up -d --build
            docker image prune -f